# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechnologyAssessmentApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TechnologyAssessmentApp

  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 4.0'

  target 'TechnologyAssessmentAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TechnologyAssessmentAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
